# إعدادات عامة
keywords:
  arabic:
    - "عقارات سوريا"
    - "شقق للبيع في سوريا"
    # … rest of arabic keywords …
  english:
    - "Syria real estate"
    # … rest of english keywords …
bing_api_key: ""   # مفتاح مصدّر من Azure
export:
  formats:
    - csv
    - json
    - mysql
    - postgresql
storage:
  base_path: ""    # يختارها المستخدم في الواجهة
  images: "images"
scheduling:
  default_cron: "0 0 * * *"  # يوميًا عند منتصف الليل
ui:
  language: "ar"
notifications:
  toast: true
authentication:
  use_master_password: true
  # سيُطلب master password لحفظ بيانات الاعتماد مشفرة
network:
  proxy: ""
  vpn_config: ""
database:
  url: "sqlite:///realestate.db"
sites:
  - name: "ikar"
    url: "https://ikar.sy"
  - name: "opensooq"
    url: "https://sy.opensooq.com"
  - name: "yabaiti"
    url: "https://yabaiti.com"
